openapi: 3.0.0
paths:
  /cats:
    post:
      operationId: CatsController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCatDto'
      responses:
        '201':
          description: ''
    get:
      operationId: CatsController_findAll
      parameters: []
      responses:
        '200':
          description: ''
  /cats/ab*cd:
    get:
      operationId: CatsController_all
      parameters: []
      responses:
        '200':
          description: ''
  /cats/{id}:
    get:
      operationId: CatsController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
    patch:
      operationId: CatsController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCatDto'
      responses:
        '200':
          description: ''
    delete:
      operationId: CatsController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
  /todo:
    get:
      operationId: TodosController_readAllTodos
      summary: 全体取得API
      parameters: []
      responses:
        '200':
          description: 全Todoを取得
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/GetTodosRes'
      tags: &ref_0
        - /todo
    post:
      operationId: TodosController_createTodo
      summary: Todo登録API
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoInput'
      responses:
        '201':
          description: 登録したTodoを返却
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/CreateTodoRes'
      tags: *ref_0
    put:
      operationId: TodosController_updateTodo
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTodoInput'
      responses:
        '200':
          description: ''
      tags: *ref_0
  /todo/{id}:
    delete:
      operationId: TodosController_deleteTodo
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: *ref_0
  /file:
    get:
      operationId: FileController_getFile
      parameters: []
      responses:
        '200':
          description: ''
info:
  title: Cats example
  description: The cats API description
  version: '1.0'
  contact: {}
tags:
  - name: cats
    description: ''
servers: []
components:
  schemas:
    CreateCatDto:
      type: object
      properties: {}
    UpdateCatDto:
      type: object
      properties: {}
    Todo:
      type: object
      properties:
        id:
          type: string
          example: abcdefg
          description: ID
        title:
          type: string
          example: title
          description: title
        status:
          type: string
          example: status
          description: status
      required:
        - id
        - title
        - status
    GetTodosRes:
      type: object
      properties:
        todos:
          description: List of TODO items
          type: array
          items:
            $ref: '#/components/schemas/Todo'
      required:
        - todos
    CreateTodoInput:
      type: object
      properties:
        title:
          type: string
        status:
          type: string
      required:
        - title
        - status
    CreateTodoRes:
      type: object
      properties:
        id:
          type: string
          example: abcdefg
          description: ID
        title:
          type: string
          example: title
          description: title
        status:
          type: string
          example: status
          description: status
      required:
        - id
        - title
        - status
    UpdateTodoInput:
      type: object
      properties: {}
